---
  - name: Configure Ambari Server and agents 
    hosts: ambari 
    tasks: 
  
    - name: Import Ambari Tables and Structure
      mysql_db:
         name: ambari
         state: import
         target: /var/lib/ambari-server/resources/Ambari-DDL-MySQL-CREATE.sql
      ignore_errors: true

    - name: setup mysql-connector-java jars
      shell: /usr/sbin/ambari-server setup --jdbc-db=mysql --jdbc-driver=/usr/share/java/mysql-connector-java.jar

    - name: Repoint Ambari Database to Mysql 
      set_fact: 
         ambari_database_options: "--database=mysql \ 
                                   --databasehost=grj-1.field.hortonworks.com  \
                                   --databaseport=3306 \ 
                                   --databasename=ambari \
                                   --databaseusername=ambari \
                                   --databasepassword=bigdata"


   ##  If the Ambari Server  needs to be run as ambari user
   ## - name: Ambari Server RunAs
   ##   shell: sed -i 's/ambari-server.user=root/ambari-server.user=ambari/g' /etc/ambari-server/conf/ambari.properties


    - name: Repoint Ambari to use Oracle JDK 
      set_fact: 
         ambari_java_options: "-j /usr/java/default"

    - name: Basic/Silent ambari Server configuration
      shell: /usr/sbin/ambari-server setup -s {{ ambari_java_options }} {{ ambari_database_options }} 


    - name: Ambari Server restart 
      shell: /usr/sbin/ambari-server restart 


  - name: Configure Ambari Server and agents
    hosts: all
    tasks:

   ##  If the Ambari Agent needs to be run as ambari user  
   ## - name: Ambari Agent RunAs
   ##   shell: sed -i 's/run_as_user=root/run_as_user=ambari/g' /etc/ambari-agent/conf/ambari-agent.ini

    - name: Ambari Agent Repoint
      shell: sed -i 's/localhost/grj-1.field.hortonworks.com/g' /etc/ambari-agent/conf/ambari-agent.ini

    - name:
      shell: /usr/sbin/ambari-agent restart 
